### ISSUE TITLE
Is this up to date?

### ISSUE THREAD

**Issue by abhi18av** [packethost/packet-java#4]
Hi Packet Host team,

I was wondering whether this API is really up to date since the last commit was almost 2 years ago ?

**Comment by displague** [comment]
Hi @abhi18av! This response is a bit late, but I thought I'd respond since I'm reviewing the state of some of our SDKs.

I see API activity from this client, so presumably this project is still functioning.
Over the past 3 years, the API hasn't changed in a breaking way, so I would expect this.

One of the key features missing from this client is support for Metros.

A generated client could be produced with the following:

```sh
mkdir equinix-metal-java
cd equinix-metal-java
cat > Makefile <<EOS
.PHONY: generate

OPENAPI_URL=https://api.equinix.com/metal/v1/api-docs
PACKAGE=com.equinix.metal

generate:
	docker run --rm -v $(PWD):/local swaggerapi/swagger-codegen-cli generate \
		-i $(OPENAPI_URL) -l java \
		--invoker-package $(PACKAGE) \
		--api-package $(PACKAGE).api \
		--model-package $(PACKAGE).model \
		--group-id $(PACKAGE) \
		--artifact-id equinix-metal-api-client \
		--git-repo-base-url https://github.com \
		--git-repo-id equinix-metal-java \
		--git-user-id equinix-labs \
		-o /local/
EOS
make
```

A competing generator is https://github.com/OpenAPITools/openapi-generator. 

I'll follow up if an official generated replacement project emerges. In the meanwhile, feel free to give this project a try and open issues and feature requests as needed.

**Comment by abhi18av** [comment]
Thanks for looking into this @displague  :)
